## The following two functions work in conjunction in the way that 
## the output of makeCacheMatrix is the input of cacheSolve.
## makeCacheMatrix takes a matrix and generates a
## special list object which will cache the inverse of the
## input matrix when passed to the cacheSolve function.
## This means that if a specific output of cacheSolve is rerun with
## cacheSolve, the cached inverse matrix will be returned along
## with the message "getting cached data", and the computation is skipped.


## makeCacheMatrix takes a matrix (assumed invertible),
## and returns a list object capable of caching its inverse.
## The list contains four functions which can:
## - set the matrix (function: "set")
## - get the matrix (function: "get")
## - set the inverse of the matrix (function: "setsolve")
## - get the inverse of the matrix (function: "getsolve")

makeCacheMatrix <- function(x = matrix()) {
  s <- NULL
  set <- function(y){
    x <<- y
    s <<- NULL
  }
  get <- function() x
  setsolve <- function(solve) s <<- solve
  getsolve <- function() s
  list(set = set, get = get,
       setsolve = setsolve,
       getsolve = getsolve)
}


## cacheSolve checks if the object generated by makeCacheMatrix
## has the inverse matrix cached, if so, this is returned.
## If the cached value is NULL, the inverse of the matrix initially
## passed to makeCacheMatrix is calculated, cached in x and returned.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  s <- x$getsolve()
  if(!is.null(s)){
    message("getting cached data")
    return(s)
  }
  data <- x$get()
  s <- solve(data, ...)
  x$setsolve(s)
  s
}



